version: '3.6'
services:
  php:
    container_name: cmath10-mapper-bundle-php
    build: docker/services/php
    environment:
      PHP_IDE_CONFIG: "serverName=cmath10/mapper-bundle"
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST}
    volumes:
      - ./:/var/www/mapper-bundle
      - ./docker/services/php/php.ini:/usr/local/etc/php/conf.d/docker-php-override.ini
      - ./docker/services/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - $SSH_AUTH_SOCK:/ssh-auth.sock
